prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false

prometheusOperator:
  createCustomResource: false

grafana:
  adminPassword: OtusPassword!