apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: app
spec:
  containers:
  - name: web
    image: funkypenguin18/otus-nginx:v.02
    volumeMounts:
    - name: app
      mountPath: "/app"
  initContainers:
  - name: install
    image: busybox
    command:
      - 'sh'
      - '-c'
      - 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh'
    volumeMounts:
    - name: app
      mountPath: "/app"
  volumes:
  - name: app
    emptyDir: {}
